Byrth.Web/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Byrth.Core;
using Byrth.Web.Models;
using Twilio;

namespace Byrth.Web.Controllers
{
    [Authorize]
    public class ContactsController : BaseController
    {
        // GET: Contacts
        public ActionResult Index()
        {
            return View(db.Contacts.Where(x => x.User.Id == CurrentUser.Id).ToList());
        }

       // GET: DueDateCountdown
       public ActionResult Countdown()
        {
            var dayCount = CurrentUser.DaysTilDue;
            return View((object)dayCount);

        }

        // GET: Contacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null || !CurrentUser.Contacts.Any(c => c.Id == id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Phone")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                contact.User = CurrentUser;
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null || !CurrentUser.Contacts.Any(c => c.Id == id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Phone")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Byrth.Web/Controllers/HospitalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Byrth.Core;

namespace Byrth.Web.Controllers
{
    [Authorize]
    public class HospitalsController : BaseController
    {
        // GET: Hospitals
        public ActionResult Index()
        {
            if(CurrentUser.Hospital != null)
            {
                return View(CurrentUser.Hospital);
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        // GET: Hospitals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = CurrentUser.Hospital;
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // GET: Hospitals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospitals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,City,State,Zipcode,Phone")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                if (CurrentUser.Hospital == null)
                {
                    CurrentUser.Hospital = hospital;
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospital);
        }

        // GET: Hospitals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = CurrentUser.Hospital;
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // POST: Hospitals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,City,State,Zipcode,Phone")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital);
        }

        // GET: Hospitals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = CurrentUser.Hospital;
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // POST: Hospitals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hospital hospital = CurrentUser.Hospital;
            db.Hospitals.Remove(hospital);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Byrth.Web/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Twilio;
using System.Configuration;
using Byrth.Core;
using Byrth.Web.Models;

namespace Byrth.Web.Controllers
{
    [Authorize]
    public class SMSController : BaseController
    {
        
        // GET: SMSMvc
        public ActionResult Index()
        {
            var messages = db.Messages.Where(x => x.User.Id == CurrentUser.Id && x.Recipient.Phone != null).Include(r => r.Recipient);
            return View(messages);
        }

        // GET: SMSMvc/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMS sMS = CurrentUser.Messages.FirstOrDefault(m => m.Id == id);
            if (sMS == null)
            {
                return HttpNotFound();
            }
            return View(sMS);
        }

        // GET: SMSMvc/Create
        public ActionResult Create(int? recipientId)
        {
            var model = new SMSCreateVM();
            model.MyContacts = new SelectList(CurrentUser.Contacts, "Id", "FullName", recipientId.GetValueOrDefault());
            
            return View(model);
        }

        // POST: SMSMvc/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SMSCreateVM sMS)
        {
            if (ModelState.IsValid)
            {
                SMS newMessage = new SMS { Recipient = db.Contacts.Find(sMS.SelectContactId) , Body = sMS.Body, User = CurrentUser};
                db.Contacts.FirstOrDefault(m => m.Id == newMessage.Recipient.Id).Messages.Add(newMessage);
                db.SaveChanges();
                Success($"SMS ready to be sent to {newMessage.Recipient.FullName}");
                return RedirectToAction("Index");
            }

            sMS.MyContacts = new SelectList(CurrentUser.Contacts, "Id", "FullName", sMS.SelectContactId);
            db.SaveChanges();
            return View(sMS);
        }

        // GET: SMSMvc/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMS sMS = db.Messages.Find(id);
            if (sMS == null)
            {
                return HttpNotFound();
            }
            return View(sMS);
        }

        // POST: SMSMvc/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Body,Recipient")] SMS sMS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sMS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sMS);
        }

        // GET: SMSMvc/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SMS sMS = db.Messages.Find(id);
            if (sMS == null)
            {
                return HttpNotFound();
            }
            return View(sMS);
        }

        // POST: SMSMvc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SMS sMS = db.Messages.Find(id);
            db.Messages.Remove(sMS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Send(string number, string body, int id)
        {
            SendText(number, body);
            var message = db.Messages.FirstOrDefault(m => m.Id == id);
            message.IsSent = true;
            db.SaveChanges();
            return Content("Ok");
        }

        //SendText method
        public static void SendText(string number, string body)
        {
            string AccountSid = ConfigurationManager.AppSettings["acctSid"];
            string AuthToken = ConfigurationManager.AppSettings["authToken"];
            var twilio = new TwilioRestClient(AccountSid, AuthToken);

            var message = twilio.SendMessage(ConfigurationManager.AppSettings["twilioNumber"], number, body);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Byrth.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="body" class="lightSwitch">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Byrth", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><i class="visible-xs-inline glyphicon glyphicon-home"></i> Home</a></li>
                    <li><a href="@Url.Action("Index", "SMS")"><i class="visible-xs-inline glyphicon glyphicon-envelope"></i> Messaging </a></li>
                    <li><a href="@Url.Action("Index", "Contacts")"><i class="visible-xs-inline glyphicon glyphicon-user"></i> Contacts</a></li>
                    <li><a href="@Url.Action("Index", "Contractions")"><i class="visible-xs-inline glyphicon glyphicon-time"></i> Contraction Timer</a></li>
                    <li><a href="@Url.Action("Index", "Hospitals")"><i class="visible-xs-inline glyphicon glyphicon-header"></i> Hospital</a></li>
                    <li class="visible-xs-inline"><a href="#" class="tgl" value="Day"><i class="glyphicon glyphicon-lamp"></i> Lights On/Off</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">


        @if (TempData["success"] != null)
        {
            <br />
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Success!</strong> @TempData["success"]
            </div>

        }

        @if (TempData["error"] != null)
        {
            <br />
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Success!</strong> @TempData["error"]
            </div>

        }

        @RenderBody()
        <footer class="col-md-12">
            <div class="col-md-offset-10">
                &copy; @DateTime.Now.Year - Byrth
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $('.tgl').click(function () {
            var toggle = $(this);
            if (toggle.prop('value') == 'Day') {
                toggle.prop('value', 'Night');
                body.className = "darkSwitch";
            }
            else {
                toggle.prop('value', 'Day');
                body.className = "lightSwitch";
            }

        });
    </script>
</body>
</html>